const objData = (data) => {
  const accumulatedData = data.reduce(
    (acc, curr) => {
      return {
        pkb1: acc.pkb1 + curr.pkb1,
        pkb2: acc.pkb2 + curr.pkb2,
        pkb3: acc.pkb3 + curr.pkb3,
        pkb4: acc.pkb4 + curr.pkb4,
        pkb5: acc.pkb5 + curr.pkb5,
        pkb6: acc.pkb6 + curr.pkb6,
        pkb7: acc.pkb7 + curr.pkb7,
        gerindra1: acc.gerindra1 + curr.gerindra1,
        gerindra2: acc.gerindra2 + curr.gerindra2,
        gerindra3: acc.gerindra3 + curr.gerindra3,
        gerindra4: acc.gerindra4 + curr.gerindra4,
        gerindra5: acc.gerindra5 + curr.gerindra5,
        gerindra6: acc.gerindra6 + curr.gerindra6,
        gerindra7: acc.gerindra7 + curr.gerindra7,
        pdip1: acc.pdip1 + curr.pdip1,
        pdip2: acc.pdip2 + curr.pdip2,
        pdip3: acc.pdip3 + curr.pdip3,
        pdip4: acc.pdip4 + curr.pdip4,
        pdip5: acc.pdip5 + curr.pdip5,
        pdip6: acc.pdip6 + curr.pdip6,
        pdip7: acc.pdip7 + curr.pdip7,
        golkar1: acc.golkar1 + curr.golkar1,
        golkar2: acc.golkar2 + curr.golkar2,
        golkar3: acc.golkar3 + curr.golkar3,
        golkar4: acc.golkar4 + curr.golkar4,
        golkar5: acc.golkar5 + curr.golkar5,
        golkar6: acc.golkar6 + curr.golkar6,
        golkar7: acc.golkar7 + curr.golkar7,
        nasdem1: acc.nasdem1 + curr.nasdem1,
        nasdem2: acc.nasdem2 + curr.nasdem2,
        nasdem3: acc.nasdem3 + curr.nasdem3,
        nasdem4: acc.nasdem4 + curr.nasdem4,
        nasdem5: acc.nasdem5 + curr.nasdem5,
        nasdem6: acc.nasdem6 + curr.nasdem6,
        nasdem7: acc.nasdem7 + curr.nasdem7,
        buruh1: acc.buruh1 + curr.buruh1,
        buruh2: acc.buruh2 + curr.buruh2,
        buruh3: acc.buruh3 + curr.buruh3,
        buruh4: acc.buruh4 + curr.buruh4,
        buruh5: acc.buruh5 + curr.buruh5,
        buruh6: acc.buruh6 + curr.buruh6,
        buruh7: acc.buruh7 + curr.buruh7,
        gelora1: acc.gelora1 + curr.gelora1,
        gelora2: acc.gelora2 + curr.gelora2,
        gelora3: acc.gelora3 + curr.gelora3,
        gelora4: acc.gelora4 + curr.gelora4,
        gelora5: acc.gelora5 + curr.gelora5,
        gelora6: acc.gelora6 + curr.gelora6,
        gelora7: acc.gelora7 + curr.gelora7,
        pks1: acc.pks1 + curr.pks1,
        pks2: acc.pks2 + curr.pks2,
        pks3: acc.pks3 + curr.pks3,
        pks4: acc.pks4 + curr.pks4,
        pks5: acc.pks5 + curr.pks5,
        pks6: acc.pks6 + curr.pks6,
        pks7: acc.pks7 + curr.pks7,
        pkn1: acc.pkn1 + curr.pkn1,
        pkn2: acc.pkn2 + curr.pkn2,
        pkn3: acc.pkn3 + curr.pkn3,
        pkn4: acc.pkn4 + curr.pkn4,
        pkn5: acc.pkn5 + curr.pkn5,
        pkn6: acc.pkn6 + curr.pkn6,
        hanura1: acc.hanura1 + curr.hanura1,
        hanura2: acc.hanura2 + curr.hanura2,
        hanura3: acc.hanura3 + curr.hanura3,
        hanura4: acc.hanura4 + curr.hanura4,
        hanura5: acc.hanura5 + curr.hanura5,
        hanura6: acc.hanura6 + curr.hanura6,
        hanura7: acc.hanura7 + curr.hanura7,
        garda1: acc.garda1 + curr.garda1,
        garda2: acc.garda2 + curr.garda2,
        garda3: acc.garda3 + curr.garda3,
        garda4: acc.garda4 + curr.garda4,
        garda5: acc.garda5 + curr.garda5,
        garda6: acc.garda6 + curr.garda6,
        pan1: acc.pan1 + curr.pan1,
        pan2: acc.pan2 + curr.pan2,
        pan3: acc.pan3 + curr.pan3,
        pan4: acc.pan4 + curr.pan4,
        pan5: acc.pan5 + curr.pan5,
        pan6: acc.pan6 + curr.pan6,
        pan7: acc.pan7 + curr.pan7,
        demokrat1: acc.demokrat1 + curr.demokrat1,
        demokrat2: acc.demokrat2 + curr.demokrat2,
        demokrat3: acc.demokrat3 + curr.demokrat3,
        demokrat4: acc.demokrat4 + curr.demokrat4,
        demokrat5: acc.demokrat5 + curr.demokrat5,
        demokrat6: acc.demokrat6 + curr.demokrat6,
        demokrat7: acc.demokrat7 + curr.demokrat7,
        psi1: acc.psi1 + curr.psi1,
        psi2: acc.psi2 + curr.psi2,
        psi3: acc.psi3 + curr.psi3,
        psi4: acc.psi4 + curr.psi4,
        psi5: acc.psi5 + curr.psi5,
        psi6: acc.psi6 + curr.psi6,
        psi7: acc.psi7 + curr.psi7,
        perindo1: acc.perindo1 + curr.perindo1,
        perindo2: acc.perindo2 + curr.perindo2,
        perindo3: acc.perindo3 + curr.perindo3,
        perindo4: acc.perindo4 + curr.perindo4,
        perindo5: acc.perindo5 + curr.perindo5,
        perindo6: acc.perindo6 + curr.perindo6,
        perindo7: acc.perindo7 + curr.perindo7,
        ppp1: acc.ppp1 + curr.ppp1,
        ppp2: acc.ppp2 + curr.ppp2,
        ppp3: acc.ppp3 + curr.ppp3,
        ppp4: acc.ppp4 + curr.ppp4,
        ppp5: acc.ppp5 + curr.ppp5,
        ppp6: acc.ppp6 + curr.ppp6,
        ppp7: acc.ppp7 + curr.ppp7,
        umat1: acc.umat1 + curr.umat1,
        umat2: acc.umat2 + curr.umat2,
        umat3: acc.umat3 + curr.umat3,
        umat4: acc.umat4 + curr.umat4,
        umat5: acc.umat5 + curr.umat5,
        umat6: acc.umat6 + curr.umat6,
        umat7: acc.umat7 + curr.umat7,
      };
    },
    {
      pkb1: 0,
      pkb2: 0,
      pkb3: 0,
      pkb4: 0,
      pkb5: 0,
      pkb6: 0,
      pkb7: 0,
      gerindra1: 0,
      gerindra2: 0,
      gerindra3: 0,
      gerindra4: 0,
      gerindra5: 0,
      gerindra6: 0,
      gerindra7: 0,
      pdip1: 0,
      pdip2: 0,
      pdip3: 0,
      pdip4: 0,
      pdip5: 0,
      pdip6: 0,
      pdip7: 0,
      golkar1: 0,
      golkar2: 0,
      golkar3: 0,
      golkar4: 0,
      golkar5: 0,
      golkar6: 0,
      golkar7: 0,
      nasdem1: 0,
      nasdem2: 0,
      nasdem3: 0,
      nasdem4: 0,
      nasdem5: 0,
      nasdem6: 0,
      nasdem7: 0,
      buruh1: 0,
      buruh2: 0,
      buruh3: 0,
      buruh4: 0,
      buruh5: 0,
      buruh6: 0,
      buruh7: 0,
      gelora1: 0,
      gelora2: 0,
      gelora3: 0,
      gelora4: 0,
      gelora5: 0,
      gelora6: 0,
      gelora7: 0,
      pks1: 0,
      pks2: 0,
      pks3: 0,
      pks4: 0,
      pks5: 0,
      pks6: 0,
      pks7: 0,
      pkn1: 0,
      pkn2: 0,
      pkn3: 0,
      pkn4: 0,
      pkn5: 0,
      pkn6: 0,
      hanura1: 0,
      hanura2: 0,
      hanura3: 0,
      hanura4: 0,
      hanura5: 0,
      hanura6: 0,
      hanura7: 0,
      garda1: 0,
      garda2: 0,
      garda3: 0,
      garda4: 0,
      garda5: 0,
      garda6: 0,
      pan1: 0,
      pan2: 0,
      pan3: 0,
      pan4: 0,
      pan5: 0,
      pan6: 0,
      pan7: 0,
      demokrat1: 0,
      demokrat2: 0,
      demokrat3: 0,
      demokrat4: 0,
      demokrat5: 0,
      demokrat6: 0,
      demokrat7: 0,
      psi1: 0,
      psi2: 0,
      psi3: 0,
      psi4: 0,
      psi5: 0,
      psi6: 0,
      psi7: 0,
      perindo1: 0,
      perindo2: 0,
      perindo3: 0,
      perindo4: 0,
      perindo5: 0,
      perindo6: 0,
      perindo7: 0,
      ppp1: 0,
      ppp2: 0,
      ppp3: 0,
      ppp4: 0,
      ppp5: 0,
      ppp6: 0,
      ppp7: 0,
      umat1: 0,
      umat2: 0,
      umat3: 0,
      umat4: 0,
      umat5: 0,
      umat6: 0,
      umat7: 0,
    }
  );
  console.log("INI DATA ACCUMULASI");
  return accumulatedData;
};

const mappingData = (data) => {
  const hasil = data.map((obj) => {
    const {
      pkb1,
      pkb2,
      pkb3,
      pkb4,
      pkb5,
      pkb6,
      pkb7,
      gerindra1,
      gerindra2,
      gerindra3,
      gerindra4,
      gerindra5,
      gerindra6,
      gerindra7,
      pdip1,
      pdip2,
      pdip3,
      pdip4,
      pdip5,
      pdip6,
      pdip7,
      golkar1,
      golkar2,
      golkar3,
      golkar4,
      golkar5,
      golkar6,
      golkar7,
      nasdem1,
      nasdem2,
      nasdem3,
      nasdem4,
      nasdem5,
      nasdem6,
      nasdem7,
      buruh1,
      buruh2,
      buruh3,
      buruh4,
      buruh5,
      buruh6,
      buruh7,
      gelora1,
      gelora2,
      gelora3,
      gelora4,
      gelora5,
      gelora6,
      gelora7,
      pks1,
      pks2,
      pks3,
      pks4,
      pks5,
      pks6,
      pks7,
      pkn1,
      pkn2,
      pkn3,
      pkn4,
      pkn5,
      pkn6,
      hanura1,
      hanura2,
      hanura3,
      hanura4,
      hanura5,
      hanura6,
      hanura7,
      garda1,
      garda2,
      garda3,
      garda4,
      garda5,
      garda6,
      pan1,
      pan2,
      pan3,
      pan4,
      pan5,
      pan6,
      pan7,
      demokrat1,
      demokrat2,
      demokrat3,
      demokrat4,
      demokrat5,
      demokrat6,
      demokrat7,
      psi1,
      psi2,
      psi3,
      psi4,
      psi5,
      psi6,
      psi7,
      perindo1,
      perindo2,
      perindo3,
      perindo4,
      perindo5,
      perindo6,
      perindo7,
      ppp1,
      ppp2,
      ppp3,
      ppp4,
      ppp5,
      ppp6,
      ppp7,
      umat1,
      umat2,
      umat3,
      umat4,
      umat5,
      umat6,
      umat7,
    } = obj;
    return {
      pkb1,
      pkb2,
      pkb3,
      pkb4,
      pkb5,
      pkb6,
      pkb7,
      gerindra1,
      gerindra2,
      gerindra3,
      gerindra4,
      gerindra5,
      gerindra6,
      gerindra7,
      pdip1,
      pdip2,
      pdip3,
      pdip4,
      pdip5,
      pdip6,
      pdip7,
      golkar1,
      golkar2,
      golkar3,
      golkar4,
      golkar5,
      golkar6,
      golkar7,
      nasdem1,
      nasdem2,
      nasdem3,
      nasdem4,
      nasdem5,
      nasdem6,
      nasdem7,
      buruh1,
      buruh2,
      buruh3,
      buruh4,
      buruh5,
      buruh6,
      buruh7,
      gelora1,
      gelora2,
      gelora3,
      gelora4,
      gelora5,
      gelora6,
      gelora7,
      pks1,
      pks2,
      pks3,
      pks4,
      pks5,
      pks6,
      pks7,
      pkn1,
      pkn2,
      pkn3,
      pkn4,
      pkn5,
      pkn6,
      hanura1,
      hanura2,
      hanura3,
      hanura4,
      hanura5,
      hanura6,
      hanura7,
      garda1,
      garda2,
      garda3,
      garda4,
      garda5,
      garda6,
      pan1,
      pan2,
      pan3,
      pan4,
      pan5,
      pan6,
      pan7,
      demokrat1,
      demokrat2,
      demokrat3,
      demokrat4,
      demokrat5,
      demokrat6,
      demokrat7,
      psi1,
      psi2,
      psi3,
      psi4,
      psi5,
      psi6,
      psi7,
      perindo1,
      perindo2,
      perindo3,
      perindo4,
      perindo5,
      perindo6,
      perindo7,
      ppp1,
      ppp2,
      ppp3,
      ppp4,
      ppp5,
      ppp6,
      ppp7,
      umat1,
      umat2,
      umat3,
      umat4,
      umat5,
      umat6,
      umat7,
    };
  });
  console.log("INI DATA ACCUMULASI MAPPING");

  return hasil;
};

export { objData, mappingData };
